INSERT INTO  ACCOUNT (ID, ACCOUNTNUMBER, FIRSTNAME, LASTNAME) 
VALUES (1, 1234, 'John', 'Doe');
INSERT INTO  ACCOUNT (ID, ACCOUNTNUMBER, FIRSTNAME, LASTNAME) VALUES (2, 1235, 'Jane', 'Doe');
INSERT INTO  ACCOUNT (ID, ACCOUNTNUMBER, FIRSTNAME, LASTNAME) VALUES (3, 1236, 'Jim', 'Taylor');
